# Generated by Django 2.0.2 on 2018-02-08 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20180208_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_truck',
            name='garage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.Garage'),
            preserve_default=False,
        ),
    ]
