# Generated by Django 2.0.2 on 2018-02-08 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20180208_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_truck',
            name='garage',
        ),
        migrations.AddField(
            model_name='garage',
            name='model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.Model_truck'),
            preserve_default=False,
        ),
    ]
